name: syc
description: "A new Flutter project."
publish_to: "none"

version: 1.0.3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  shared_preferences: ^2.0.11
  go_router: ^13.0.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  image_picker: ^1.2.0
  timeago: ^3.7.1
  flutter_html: ^3.0.0
  permission_handler: ^12.0.1
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  font_awesome_flutter: ^10.8.0
  html: ^0.15.6
  dom_tools: ^2.3.5
  share_plus: ^11.0.0
  package_info_plus: ^8.3.0
  qr_flutter: ^4.1.0
  qr_code_scanner_plus: ^2.0.10+1
  encrypt: ^5.0.3
  image_cropper: ^10.0.0
  flutter_image_compress: ^2.4.0
  app_badge_plus: ^1.2.3
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^19.4.2
  device_info_plus: ^12.1.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^5.0.0

# icon app
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/appicon4.png" 
  min_sdk_android: 21 

flutter:
  assets:
    - assets/images/event.jpg
    - assets/images/background_login.jpg #compressed
    - assets/images/background_secret.jpg
    - assets/images/background_email.png #compressed
    - assets/images/background_form.png
    - assets/images/data_not_found.png
    - assets/images/answer_saved_success.png
    - assets/images/answer_saved_fail.png
    - assets/images/read_saved_success.png
    - assets/images/read_saved_fail.png
    - assets/images/verified_success.png
    - assets/images/verified_fail.png
    - assets/images/megaphone.png #compressed
    - assets/images/background_profile.png
    - assets/images/background_dashboard.png
    - assets/images/background_fade.jpg
    - assets/images/background_anggota.jpg
    - assets/images/background_list_bacaan.jpg
    - assets/images/card_dashboard_komitmen.png
    - assets/images/card_dashboard_role.png
    - assets/images/card_komitmen3.jpg
    - assets/images/card_bacaan.png
    - assets/images/card_kontak.jpg
    - assets/images/card_dokumentasi.jpg
    - assets/images/card_tutorial.png
    - assets/images/card_devotion.jpg
    - assets/images/background_pengumuman.jpg

    - assets/icons/profile.svg

    # icons for login
    - assets/icons/login/show_password.svg
    - assets/icons/login/hide_password.svg

    # icons for navigation bar
    - assets/icons/navigation_bar/dashboard.svg
    - assets/icons/navigation_bar/kelompok.svg
    - assets/icons/navigation_bar/kelompok_pendaftaran.svg
    - assets/icons/navigation_bar/list_acara.svg
    - assets/icons/navigation_bar/materi.svg
    - assets/icons/navigation_bar/profile.svg

    # texts
    - assets/texts/evaluasi.png
    - assets/texts/komitmen.png
    - assets/texts/hello.png
    - assets/texts/events.png
    - assets/texts/daftar_gereja.png
    - assets/texts/daftar_kelompok.png
    - assets/texts/daftar_acara.png
    - assets/texts/daftar_grup_pendaftaran.png
    - assets/texts/daftar_grup_gereja.png
    - assets/texts/materi.png
    - assets/texts/tutorial.png
    - assets/texts/devotion.png

    # logos
    - assets/logos/appicon4.png #untuk share verse
    - assets/logos/appicon5.png #untuk snackbar back button, share verse
    - assets/logos/redeemed_text.png
    - assets/logos/stt_saat.png

    #mockups
    - assets/mockups/bible_reading.jpg #dashboard
    - assets/mockups/bkc.jpg 
    - assets/mockups/bkc2.jpg 
    - assets/mockups/kkr2.jpg 
    - assets/mockups/kkr3.jpg 
    - assets/mockups/talks.jpg 
    - assets/mockups/drama_musikal.jpg 
    - assets/mockups/opening.jpg 
    - assets/mockups/closing.jpg 
    - assets/mockups/special.jpg 
    - assets/mockups/registration.jpg 
    - assets/mockups/devotion.jpg
    - assets/mockups/amongus.jpg
    - assets/mockups/preparation.jpg
    - assets/mockups/activity.jpg
    - assets/mockups/rest.jpg
    - assets/mockups/awg.jpg
    - assets/mockups/bonding.jpg
    - assets/mockups/eat.jpg
    - assets/mockups/seeyou.jpg

    # share verse
    - assets/shareverse/photo1.png
    - assets/shareverse/photo2.png
    - assets/shareverse/photo3.png
    - assets/shareverse/photo4.png
    - assets/shareverse/photostory1.png
    - assets/shareverse/photostory2.png
    - assets/shareverse/photostory3.png
    - assets/shareverse/photostory4.png
    - assets/shareverse/photosquare1.png
    - assets/shareverse/photosquare2.png
    - assets/shareverse/photosquare3.png
    - assets/shareverse/photosquare4.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-BoldCondensed.ttf
        - asset: assets/fonts/Roboto/Roboto-BoldCondensedItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Condensed.ttf
        - asset: assets/fonts/Roboto/Roboto-CondensedItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf

    - family: Geist
      fonts:
        - asset: assets/fonts/Geist/static/Geist-Black.ttf
        - asset: assets/fonts/Geist/static/Geist-Bold.ttf
        - asset: assets/fonts/Geist/static/Geist-ExtraBold.ttf
        - asset: assets/fonts/Geist/static/Geist-ExtraLight.ttf
        - asset: assets/fonts/Geist/static/Geist-Light.ttf
        - asset: assets/fonts/Geist/static/Geist-Medium.ttf
        - asset: assets/fonts/Geist/static/Geist-Regular.ttf
        - asset: assets/fonts/Geist/static/Geist-SemiBold.ttf
        - asset: assets/fonts/Geist/static/Geist-Thin.ttf

  uses-material-design: true
